name: shortly
dependencies:
  - python=3.12.11
  - pip
  - pip:
      - coloredlogs==15.0.1
      - humanize==4.12.3
      - peewee==3.18.1
      - pydocstyle==6.3.0
      - python-dotenv==1.1.0
      - ruff==0.11.13
      - tqdm==4.67.1
      - typeguard==4.4.3
      - vulture==2.14
