name: shortly
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.10
  - pip=25.1.1
  - pip:
      - coloredlogs==15.0.1   # Logging library
      - humanize==4.12.3      # Humanize library for better readability
      - peewee==3.18.1        # ORM for SQLite
      - python-dotenv==1.1.0  # Environment variable management
      - ruff==0.11.13         # Linter for Python code
      - tqdm==4.67.1          # Progress bar library
      - typeguard==4.4.3      # Runtime type checking
      - vulture==2.14         # Code analysis tool
